// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function CheckCallHealth(arg1:string):Promise<string>;

export function GetDefaultConfig():Promise<core.EngineConfig>;

export function GetMetrics():Promise<core.EngineMetrics>;

export function StartTunnel(arg1:core.EngineConfig):Promise<void>;

export function StopTunnel():Promise<void>;
