// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCallHealth(arg1) {
  return window['go']['main']['App']['CheckCallHealth'](arg1);
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
